dubbo:
  application:
    name: backend-dubbo-server
  protocol:
    name: dubbo
    port: 12345
  registry:
    address: nacos://localhost:10086

spring:
  application:
    name: dubbo-server

server:
  port: 8083


api-gateway:
  registerAddress: 127.0.0.1:10086
  env: dev
  gray: false